// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'modules/auth/models/local/auth_token_box.dart';
import 'modules/categories/models/local/category_box.dart';
import 'modules/delivery_address/models/local/delivery_address_box.dart';
import 'modules/payment_method/models/local/payment_method_box.dart';
import 'modules/products/models/local/order_box.dart';
import 'modules/products/models/local/ordered_product_box.dart';
import 'modules/products/models/local/product_box.dart';
import 'modules/settings/models/local/settings_box.dart';
import 'modules/specifications/models/local/specification_box.dart';
import 'modules/user/models/local/user_box.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 3856635327591682795),
    name: 'AuthTokenBox',
    lastPropertyId: const obx_int.IdUid(3, 2240989312706984646),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8539764337797621889),
        name: 'id',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5444154927122119039),
        name: 'accessToken',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2240989312706984646),
        name: 'refreshToken',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 6588749362085246395),
    name: 'CategoryBox',
    lastPropertyId: const obx_int.IdUid(5, 6596917986225325277),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2935358745194349876),
        name: 'idCategory',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6130249203168466294),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2207818262752517523),
        name: 'level',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3026138744747973294),
        name: 'parent',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6596917986225325277),
        name: 'productId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 4076636637995007395),
        relationTarget: 'ProductBox',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 4862193710388650705),
    name: 'DeliveryAddressBox',
    lastPropertyId: const obx_int.IdUid(9, 4502438580958134673),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8347409311546702188),
        name: 'id',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2615980680226642964),
        name: 'deliveryType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6904968481862420745),
        name: 'comments',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3283986928304139576),
        name: 'pickupLocation',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5241384228407310243),
        name: 'country',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5108640095488037042),
        name: 'region',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4193379407663484753),
        name: 'city',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5377776534099525938),
        name: 'postalCode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 4502438580958134673),
        name: 'address',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 8034763726655406762),
    name: 'OrderBox',
    lastPropertyId: const obx_int.IdUid(4, 3182541634927413315),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6593568970208168106),
        name: 'dateTime',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7922894862689685042),
        name: 'idOrder',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3182541634927413315),
        name: 'idUser',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'products',
        srcEntity: 'OrderedProductBox',
        srcField: 'order',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 3602256631880212781),
    name: 'OrderedProductBox',
    lastPropertyId: const obx_int.IdUid(6, 7299112071734427587),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6979268622162676618),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6659406093051995712),
        name: 'idProduct',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2164292911630885146),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3091929395464094093),
        name: 'imageUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8155854713773569913),
        name: 'price',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7299112071734427587),
        name: 'quantity',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(1, 2027989821957819426),
        name: 'order',
        targetId: const obx_int.IdUid(4, 8034763726655406762),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 5501779053459729389),
    name: 'PaymentMethodBox',
    lastPropertyId: const obx_int.IdUid(3, 255251100477645359),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1510078743884079566),
        name: 'id',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6575525366744234479),
        name: 'key',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 255251100477645359),
        name: 'titleKey',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(7, 6310939426835682328),
    name: 'ProductBox',
    lastPropertyId: const obx_int.IdUid(9, 3409942711181790000),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 878126777885136887),
        name: 'idProduct',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1310805492695537330),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7006827004754936453),
        name: 'price',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1554186340567572453),
        name: 'discount',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 423136456208145548),
        name: 'discountedPrice',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4683571257868174000),
        name: 'imageUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7879631957632416330),
        name: 'marks',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5559386098013541726),
        name: 'stock',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 3409942711181790000),
        name: 'description',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'categories',
        srcEntity: 'CategoryBox',
        srcField: 'product',
      ),
      obx_int.ModelBacklink(
        name: 'specifications',
        srcEntity: 'SpecificationBox',
        srcField: 'product',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(8, 7333957506559352319),
    name: 'SettingsBox',
    lastPropertyId: const obx_int.IdUid(2, 5200045210148757342),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8345664376264946992),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5200045210148757342),
        name: 'hasAgreedTerms',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(9, 5659215725768256222),
    name: 'SpecificationBox',
    lastPropertyId: const obx_int.IdUid(5, 2125103283209966275),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4626341047177097688),
        name: 'idSpec',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1284007432166717047),
        name: 'attributeId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7317834356239714269),
        name: 'attributeName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2983247714254463943),
        name: 'value',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2125103283209966275),
        name: 'productId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(2, 2689050374580262887),
        relationTarget: 'ProductBox',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(10, 7704364882485285291),
    name: 'UserBox',
    lastPropertyId: const obx_int.IdUid(9, 5627198348544040676),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 160748080321089508),
        name: 'idUser',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8618513636004590085),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1200542389815450161),
        name: 'surname',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7285352877211304754),
        name: 'number',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6782924260364781228),
        name: 'dialCode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5553277734072297575),
        name: 'email',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7101872098900750099),
        name: 'imageUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7976830579674488356),
        name: 'deliveryAddressBoxId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(3, 6599968955173342914),
        relationTarget: 'DeliveryAddressBox',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 5627198348544040676),
        name: 'paymentMethodBoxId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(4, 4776232646091925867),
        relationTarget: 'PaymentMethodBox',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(10, 7704364882485285291),
    lastIndexId: const obx_int.IdUid(4, 4776232646091925867),
    lastRelationId: const obx_int.IdUid(1, 2027989821957819426),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [740774872330869993],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    AuthTokenBox: obx_int.EntityDefinition<AuthTokenBox>(
      model: _entities[0],
      toOneRelations: (AuthTokenBox object) => [],
      toManyRelations: (AuthTokenBox object) => {},
      getId: (AuthTokenBox object) => object.id,
      setId: (AuthTokenBox object, int id) {
        object.id = id;
      },
      objectToFB: (AuthTokenBox object, fb.Builder fbb) {
        final accessTokenOffset = object.accessToken == null
            ? null
            : fbb.writeString(object.accessToken!);
        final refreshTokenOffset = object.refreshToken == null
            ? null
            : fbb.writeString(object.refreshToken!);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, accessTokenOffset);
        fbb.addOffset(2, refreshTokenOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final accessTokenParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 6);
        final refreshTokenParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final object = AuthTokenBox(
          id: idParam,
          accessToken: accessTokenParam,
          refreshToken: refreshTokenParam,
        );

        return object;
      },
    ),
    CategoryBox: obx_int.EntityDefinition<CategoryBox>(
      model: _entities[1],
      toOneRelations: (CategoryBox object) => [object.product],
      toManyRelations: (CategoryBox object) => {},
      getId: (CategoryBox object) => object.idCategory,
      setId: (CategoryBox object, int id) {
        object.idCategory = id;
      },
      objectToFB: (CategoryBox object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(6);
        fbb.addInt64(0, object.idCategory);
        fbb.addOffset(1, nameOffset);
        fbb.addInt64(2, object.level);
        fbb.addInt64(3, object.parent);
        fbb.addInt64(4, object.product.targetId);
        fbb.finish(fbb.endTable());
        return object.idCategory;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idCategoryParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final levelParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final parentParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          10,
        );
        final object = CategoryBox(
          idCategory: idCategoryParam,
          name: nameParam,
          level: levelParam,
          parent: parentParam,
        );
        object.product.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        object.product.attach(store);
        return object;
      },
    ),
    DeliveryAddressBox: obx_int.EntityDefinition<DeliveryAddressBox>(
      model: _entities[2],
      toOneRelations: (DeliveryAddressBox object) => [],
      toManyRelations: (DeliveryAddressBox object) => {},
      getId: (DeliveryAddressBox object) => object.id,
      setId: (DeliveryAddressBox object, int id) {
        object.id = id;
      },
      objectToFB: (DeliveryAddressBox object, fb.Builder fbb) {
        final deliveryTypeOffset = fbb.writeString(object.deliveryType);
        final commentsOffset = object.comments == null
            ? null
            : fbb.writeString(object.comments!);
        final pickupLocationOffset = object.pickupLocation == null
            ? null
            : fbb.writeString(object.pickupLocation!);
        final countryOffset = object.country == null
            ? null
            : fbb.writeString(object.country!);
        final regionOffset = object.region == null
            ? null
            : fbb.writeString(object.region!);
        final cityOffset = object.city == null
            ? null
            : fbb.writeString(object.city!);
        final postalCodeOffset = object.postalCode == null
            ? null
            : fbb.writeString(object.postalCode!);
        final addressOffset = object.address == null
            ? null
            : fbb.writeString(object.address!);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, deliveryTypeOffset);
        fbb.addOffset(2, commentsOffset);
        fbb.addOffset(3, pickupLocationOffset);
        fbb.addOffset(4, countryOffset);
        fbb.addOffset(5, regionOffset);
        fbb.addOffset(6, cityOffset);
        fbb.addOffset(7, postalCodeOffset);
        fbb.addOffset(8, addressOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final deliveryTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final pickupLocationParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final countryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final regionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final cityParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final postalCodeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final addressParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final commentsParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final object = DeliveryAddressBox(
          id: idParam,
          deliveryType: deliveryTypeParam,
          pickupLocation: pickupLocationParam,
          country: countryParam,
          region: regionParam,
          city: cityParam,
          postalCode: postalCodeParam,
          address: addressParam,
          comments: commentsParam,
        );

        return object;
      },
    ),
    OrderBox: obx_int.EntityDefinition<OrderBox>(
      model: _entities[3],
      toOneRelations: (OrderBox object) => [],
      toManyRelations: (OrderBox object) => {
        obx_int.RelInfo<OrderedProductBox>.toManyBacklink(1, object.idOrder):
            object.products,
      },
      getId: (OrderBox object) => object.idOrder,
      setId: (OrderBox object, int id) {
        object.idOrder = id;
      },
      objectToFB: (OrderBox object, fb.Builder fbb) {
        fbb.startTable(5);
        fbb.addInt64(1, object.dateTime.millisecondsSinceEpoch);
        fbb.addInt64(2, object.idOrder);
        fbb.addInt64(3, object.idUser);
        fbb.finish(fbb.endTable());
        return object.idOrder;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idOrderParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final dateTimeParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0),
        );
        final idUserParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final object = OrderBox(
          idOrder: idOrderParam,
          dateTime: dateTimeParam,
          idUser: idUserParam,
        );
        obx_int.InternalToManyAccess.setRelInfo<OrderBox>(
          object.products,
          store,
          obx_int.RelInfo<OrderedProductBox>.toManyBacklink(1, object.idOrder),
        );
        return object;
      },
    ),
    OrderedProductBox: obx_int.EntityDefinition<OrderedProductBox>(
      model: _entities[4],
      toOneRelations: (OrderedProductBox object) => [],
      toManyRelations: (OrderedProductBox object) => {
        obx_int.RelInfo<OrderedProductBox>.toMany(1, object.id): object.order,
      },
      getId: (OrderedProductBox object) => object.id,
      setId: (OrderedProductBox object, int id) {
        object.id = id;
      },
      objectToFB: (OrderedProductBox object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final imageUrlOffset = object.imageUrl == null
            ? null
            : fbb.writeString(object.imageUrl!);
        final priceOffset = object.price == null
            ? null
            : fbb.writeString(object.price!);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.idProduct);
        fbb.addOffset(2, titleOffset);
        fbb.addOffset(3, imageUrlOffset);
        fbb.addOffset(4, priceOffset);
        fbb.addInt64(5, object.quantity);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final idProductParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final imageUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final priceParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final quantityParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final object = OrderedProductBox(
          id: idParam,
          idProduct: idProductParam,
          title: titleParam,
          imageUrl: imageUrlParam,
          price: priceParam,
          quantity: quantityParam,
        );
        obx_int.InternalToManyAccess.setRelInfo<OrderedProductBox>(
          object.order,
          store,
          obx_int.RelInfo<OrderedProductBox>.toMany(1, object.id),
        );
        return object;
      },
    ),
    PaymentMethodBox: obx_int.EntityDefinition<PaymentMethodBox>(
      model: _entities[5],
      toOneRelations: (PaymentMethodBox object) => [],
      toManyRelations: (PaymentMethodBox object) => {},
      getId: (PaymentMethodBox object) => object.id,
      setId: (PaymentMethodBox object, int id) {
        object.id = id;
      },
      objectToFB: (PaymentMethodBox object, fb.Builder fbb) {
        final keyOffset = fbb.writeString(object.key);
        final titleKeyOffset = fbb.writeString(object.titleKey);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, keyOffset);
        fbb.addOffset(2, titleKeyOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final keyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final titleKeyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final object = PaymentMethodBox(
          id: idParam,
          key: keyParam,
          titleKey: titleKeyParam,
        );

        return object;
      },
    ),
    ProductBox: obx_int.EntityDefinition<ProductBox>(
      model: _entities[6],
      toOneRelations: (ProductBox object) => [],
      toManyRelations: (ProductBox object) => {
        obx_int.RelInfo<CategoryBox>.toOneBacklink(
          5,
          object.idProduct,
          (CategoryBox srcObject) => srcObject.product,
        ): object.categories,
        obx_int.RelInfo<SpecificationBox>.toOneBacklink(
          5,
          object.idProduct,
          (SpecificationBox srcObject) => srcObject.product,
        ): object.specifications,
      },
      getId: (ProductBox object) => object.idProduct,
      setId: (ProductBox object, int id) {
        object.idProduct = id;
      },
      objectToFB: (ProductBox object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final priceOffset = object.price == null
            ? null
            : fbb.writeString(object.price!);
        final discountOffset = object.discount == null
            ? null
            : fbb.writeString(object.discount!);
        final discountedPriceOffset = object.discountedPrice == null
            ? null
            : fbb.writeString(object.discountedPrice!);
        final imageUrlOffset = object.imageUrl == null
            ? null
            : fbb.writeString(object.imageUrl!);
        final marksOffset = object.marks == null
            ? null
            : fbb.writeString(object.marks!);
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        fbb.startTable(10);
        fbb.addInt64(0, object.idProduct);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, priceOffset);
        fbb.addOffset(3, discountOffset);
        fbb.addOffset(4, discountedPriceOffset);
        fbb.addOffset(5, imageUrlOffset);
        fbb.addOffset(6, marksOffset);
        fbb.addInt64(7, object.stock);
        fbb.addOffset(8, descriptionOffset);
        fbb.finish(fbb.endTable());
        return object.idProduct;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idProductParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final priceParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final discountParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final discountedPriceParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final imageUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final marksParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final stockParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          18,
        );
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final object = ProductBox(
          idProduct: idProductParam,
          name: nameParam,
          price: priceParam,
          discount: discountParam,
          discountedPrice: discountedPriceParam,
          imageUrl: imageUrlParam,
          marks: marksParam,
          stock: stockParam,
          description: descriptionParam,
        );
        obx_int.InternalToManyAccess.setRelInfo<ProductBox>(
          object.categories,
          store,
          obx_int.RelInfo<CategoryBox>.toOneBacklink(
            5,
            object.idProduct,
            (CategoryBox srcObject) => srcObject.product,
          ),
        );
        obx_int.InternalToManyAccess.setRelInfo<ProductBox>(
          object.specifications,
          store,
          obx_int.RelInfo<SpecificationBox>.toOneBacklink(
            5,
            object.idProduct,
            (SpecificationBox srcObject) => srcObject.product,
          ),
        );
        return object;
      },
    ),
    SettingsBox: obx_int.EntityDefinition<SettingsBox>(
      model: _entities[7],
      toOneRelations: (SettingsBox object) => [],
      toManyRelations: (SettingsBox object) => {},
      getId: (SettingsBox object) => object.id,
      setId: (SettingsBox object, int id) {
        object.id = id;
      },
      objectToFB: (SettingsBox object, fb.Builder fbb) {
        fbb.startTable(3);
        fbb.addInt64(0, object.id);
        fbb.addBool(1, object.hasAgreedTerms);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final hasAgreedTermsParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          6,
          false,
        );
        final object = SettingsBox(
          id: idParam,
          hasAgreedTerms: hasAgreedTermsParam,
        );

        return object;
      },
    ),
    SpecificationBox: obx_int.EntityDefinition<SpecificationBox>(
      model: _entities[8],
      toOneRelations: (SpecificationBox object) => [object.product],
      toManyRelations: (SpecificationBox object) => {},
      getId: (SpecificationBox object) => object.idSpec,
      setId: (SpecificationBox object, int id) {
        object.idSpec = id;
      },
      objectToFB: (SpecificationBox object, fb.Builder fbb) {
        final attributeNameOffset = fbb.writeString(object.attributeName);
        final valueOffset = fbb.writeString(object.value);
        fbb.startTable(6);
        fbb.addInt64(0, object.idSpec);
        fbb.addInt64(1, object.attributeId);
        fbb.addOffset(2, attributeNameOffset);
        fbb.addOffset(3, valueOffset);
        fbb.addInt64(4, object.product.targetId);
        fbb.finish(fbb.endTable());
        return object.idSpec;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idSpecParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final attributeIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final attributeNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final valueParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final object = SpecificationBox(
          idSpec: idSpecParam,
          attributeId: attributeIdParam,
          attributeName: attributeNameParam,
          value: valueParam,
        );
        object.product.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        object.product.attach(store);
        return object;
      },
    ),
    UserBox: obx_int.EntityDefinition<UserBox>(
      model: _entities[9],
      toOneRelations: (UserBox object) => [
        object.deliveryAddressBox,
        object.paymentMethodBox,
      ],
      toManyRelations: (UserBox object) => {},
      getId: (UserBox object) => object.idUser,
      setId: (UserBox object, int id) {
        object.idUser = id;
      },
      objectToFB: (UserBox object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final surnameOffset = fbb.writeString(object.surname);
        final numberOffset = fbb.writeString(object.number);
        final dialCodeOffset = fbb.writeString(object.dialCode);
        final emailOffset = fbb.writeString(object.email);
        final imageUrlOffset = object.imageUrl == null
            ? null
            : fbb.writeString(object.imageUrl!);
        fbb.startTable(10);
        fbb.addInt64(0, object.idUser ?? 0);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, surnameOffset);
        fbb.addOffset(3, numberOffset);
        fbb.addOffset(4, dialCodeOffset);
        fbb.addOffset(5, emailOffset);
        fbb.addOffset(6, imageUrlOffset);
        fbb.addInt64(7, object.deliveryAddressBox.targetId);
        fbb.addInt64(8, object.paymentMethodBox.targetId);
        fbb.finish(fbb.endTable());
        return object.idUser ?? 0;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idUserParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          4,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final surnameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final numberParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final dialCodeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final emailParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final imageUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final object = UserBox(
          idUser: idUserParam,
          name: nameParam,
          surname: surnameParam,
          number: numberParam,
          dialCode: dialCodeParam,
          email: emailParam,
          imageUrl: imageUrlParam,
        );
        object.deliveryAddressBox.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        object.deliveryAddressBox.attach(store);
        object.paymentMethodBox.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        object.paymentMethodBox.attach(store);
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [AuthTokenBox] entity fields to define ObjectBox queries.
class AuthTokenBox_ {
  /// See [AuthTokenBox.id].
  static final id = obx.QueryIntegerProperty<AuthTokenBox>(
    _entities[0].properties[0],
  );

  /// See [AuthTokenBox.accessToken].
  static final accessToken = obx.QueryStringProperty<AuthTokenBox>(
    _entities[0].properties[1],
  );

  /// See [AuthTokenBox.refreshToken].
  static final refreshToken = obx.QueryStringProperty<AuthTokenBox>(
    _entities[0].properties[2],
  );
}

/// [CategoryBox] entity fields to define ObjectBox queries.
class CategoryBox_ {
  /// See [CategoryBox.idCategory].
  static final idCategory = obx.QueryIntegerProperty<CategoryBox>(
    _entities[1].properties[0],
  );

  /// See [CategoryBox.name].
  static final name = obx.QueryStringProperty<CategoryBox>(
    _entities[1].properties[1],
  );

  /// See [CategoryBox.level].
  static final level = obx.QueryIntegerProperty<CategoryBox>(
    _entities[1].properties[2],
  );

  /// See [CategoryBox.parent].
  static final parent = obx.QueryIntegerProperty<CategoryBox>(
    _entities[1].properties[3],
  );

  /// See [CategoryBox.product].
  static final product = obx.QueryRelationToOne<CategoryBox, ProductBox>(
    _entities[1].properties[4],
  );
}

/// [DeliveryAddressBox] entity fields to define ObjectBox queries.
class DeliveryAddressBox_ {
  /// See [DeliveryAddressBox.id].
  static final id = obx.QueryIntegerProperty<DeliveryAddressBox>(
    _entities[2].properties[0],
  );

  /// See [DeliveryAddressBox.deliveryType].
  static final deliveryType = obx.QueryStringProperty<DeliveryAddressBox>(
    _entities[2].properties[1],
  );

  /// See [DeliveryAddressBox.comments].
  static final comments = obx.QueryStringProperty<DeliveryAddressBox>(
    _entities[2].properties[2],
  );

  /// See [DeliveryAddressBox.pickupLocation].
  static final pickupLocation = obx.QueryStringProperty<DeliveryAddressBox>(
    _entities[2].properties[3],
  );

  /// See [DeliveryAddressBox.country].
  static final country = obx.QueryStringProperty<DeliveryAddressBox>(
    _entities[2].properties[4],
  );

  /// See [DeliveryAddressBox.region].
  static final region = obx.QueryStringProperty<DeliveryAddressBox>(
    _entities[2].properties[5],
  );

  /// See [DeliveryAddressBox.city].
  static final city = obx.QueryStringProperty<DeliveryAddressBox>(
    _entities[2].properties[6],
  );

  /// See [DeliveryAddressBox.postalCode].
  static final postalCode = obx.QueryStringProperty<DeliveryAddressBox>(
    _entities[2].properties[7],
  );

  /// See [DeliveryAddressBox.address].
  static final address = obx.QueryStringProperty<DeliveryAddressBox>(
    _entities[2].properties[8],
  );
}

/// [OrderBox] entity fields to define ObjectBox queries.
class OrderBox_ {
  /// See [OrderBox.dateTime].
  static final dateTime = obx.QueryDateProperty<OrderBox>(
    _entities[3].properties[0],
  );

  /// See [OrderBox.idOrder].
  static final idOrder = obx.QueryIntegerProperty<OrderBox>(
    _entities[3].properties[1],
  );

  /// See [OrderBox.idUser].
  static final idUser = obx.QueryIntegerProperty<OrderBox>(
    _entities[3].properties[2],
  );
}

/// [OrderedProductBox] entity fields to define ObjectBox queries.
class OrderedProductBox_ {
  /// See [OrderedProductBox.id].
  static final id = obx.QueryIntegerProperty<OrderedProductBox>(
    _entities[4].properties[0],
  );

  /// See [OrderedProductBox.idProduct].
  static final idProduct = obx.QueryIntegerProperty<OrderedProductBox>(
    _entities[4].properties[1],
  );

  /// See [OrderedProductBox.title].
  static final title = obx.QueryStringProperty<OrderedProductBox>(
    _entities[4].properties[2],
  );

  /// See [OrderedProductBox.imageUrl].
  static final imageUrl = obx.QueryStringProperty<OrderedProductBox>(
    _entities[4].properties[3],
  );

  /// See [OrderedProductBox.price].
  static final price = obx.QueryStringProperty<OrderedProductBox>(
    _entities[4].properties[4],
  );

  /// See [OrderedProductBox.quantity].
  static final quantity = obx.QueryIntegerProperty<OrderedProductBox>(
    _entities[4].properties[5],
  );

  /// see [OrderedProductBox.order]
  static final order = obx.QueryRelationToMany<OrderedProductBox, OrderBox>(
    _entities[4].relations[0],
  );
}

/// [PaymentMethodBox] entity fields to define ObjectBox queries.
class PaymentMethodBox_ {
  /// See [PaymentMethodBox.id].
  static final id = obx.QueryIntegerProperty<PaymentMethodBox>(
    _entities[5].properties[0],
  );

  /// See [PaymentMethodBox.key].
  static final key = obx.QueryStringProperty<PaymentMethodBox>(
    _entities[5].properties[1],
  );

  /// See [PaymentMethodBox.titleKey].
  static final titleKey = obx.QueryStringProperty<PaymentMethodBox>(
    _entities[5].properties[2],
  );
}

/// [ProductBox] entity fields to define ObjectBox queries.
class ProductBox_ {
  /// See [ProductBox.idProduct].
  static final idProduct = obx.QueryIntegerProperty<ProductBox>(
    _entities[6].properties[0],
  );

  /// See [ProductBox.name].
  static final name = obx.QueryStringProperty<ProductBox>(
    _entities[6].properties[1],
  );

  /// See [ProductBox.price].
  static final price = obx.QueryStringProperty<ProductBox>(
    _entities[6].properties[2],
  );

  /// See [ProductBox.discount].
  static final discount = obx.QueryStringProperty<ProductBox>(
    _entities[6].properties[3],
  );

  /// See [ProductBox.discountedPrice].
  static final discountedPrice = obx.QueryStringProperty<ProductBox>(
    _entities[6].properties[4],
  );

  /// See [ProductBox.imageUrl].
  static final imageUrl = obx.QueryStringProperty<ProductBox>(
    _entities[6].properties[5],
  );

  /// See [ProductBox.marks].
  static final marks = obx.QueryStringProperty<ProductBox>(
    _entities[6].properties[6],
  );

  /// See [ProductBox.stock].
  static final stock = obx.QueryIntegerProperty<ProductBox>(
    _entities[6].properties[7],
  );

  /// See [ProductBox.description].
  static final description = obx.QueryStringProperty<ProductBox>(
    _entities[6].properties[8],
  );

  /// see [ProductBox.categories]
  static final categories = obx.QueryBacklinkToMany<CategoryBox, ProductBox>(
    CategoryBox_.product,
  );

  /// see [ProductBox.specifications]
  static final specifications =
      obx.QueryBacklinkToMany<SpecificationBox, ProductBox>(
        SpecificationBox_.product,
      );
}

/// [SettingsBox] entity fields to define ObjectBox queries.
class SettingsBox_ {
  /// See [SettingsBox.id].
  static final id = obx.QueryIntegerProperty<SettingsBox>(
    _entities[7].properties[0],
  );

  /// See [SettingsBox.hasAgreedTerms].
  static final hasAgreedTerms = obx.QueryBooleanProperty<SettingsBox>(
    _entities[7].properties[1],
  );
}

/// [SpecificationBox] entity fields to define ObjectBox queries.
class SpecificationBox_ {
  /// See [SpecificationBox.idSpec].
  static final idSpec = obx.QueryIntegerProperty<SpecificationBox>(
    _entities[8].properties[0],
  );

  /// See [SpecificationBox.attributeId].
  static final attributeId = obx.QueryIntegerProperty<SpecificationBox>(
    _entities[8].properties[1],
  );

  /// See [SpecificationBox.attributeName].
  static final attributeName = obx.QueryStringProperty<SpecificationBox>(
    _entities[8].properties[2],
  );

  /// See [SpecificationBox.value].
  static final value = obx.QueryStringProperty<SpecificationBox>(
    _entities[8].properties[3],
  );

  /// See [SpecificationBox.product].
  static final product = obx.QueryRelationToOne<SpecificationBox, ProductBox>(
    _entities[8].properties[4],
  );
}

/// [UserBox] entity fields to define ObjectBox queries.
class UserBox_ {
  /// See [UserBox.idUser].
  static final idUser = obx.QueryIntegerProperty<UserBox>(
    _entities[9].properties[0],
  );

  /// See [UserBox.name].
  static final name = obx.QueryStringProperty<UserBox>(
    _entities[9].properties[1],
  );

  /// See [UserBox.surname].
  static final surname = obx.QueryStringProperty<UserBox>(
    _entities[9].properties[2],
  );

  /// See [UserBox.number].
  static final number = obx.QueryStringProperty<UserBox>(
    _entities[9].properties[3],
  );

  /// See [UserBox.dialCode].
  static final dialCode = obx.QueryStringProperty<UserBox>(
    _entities[9].properties[4],
  );

  /// See [UserBox.email].
  static final email = obx.QueryStringProperty<UserBox>(
    _entities[9].properties[5],
  );

  /// See [UserBox.imageUrl].
  static final imageUrl = obx.QueryStringProperty<UserBox>(
    _entities[9].properties[6],
  );

  /// See [UserBox.deliveryAddressBox].
  static final deliveryAddressBox =
      obx.QueryRelationToOne<UserBox, DeliveryAddressBox>(
        _entities[9].properties[7],
      );

  /// See [UserBox.paymentMethodBox].
  static final paymentMethodBox =
      obx.QueryRelationToOne<UserBox, PaymentMethodBox>(
        _entities[9].properties[8],
      );
}
