// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'modules/categories/models/local/category_box.dart';
import 'modules/products/models/local/product_box.dart';
import 'modules/specifications/models/local/specification_box.dart';
import 'modules/user_information/models/local/delivery_address/delivery_address_box.dart';
import 'modules/user_information/models/local/payment_method/payment_method_box.dart';
import 'modules/user_information/models/local/user/user_box.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 1638919249445323337),
    name: 'CategoryBox',
    lastPropertyId: const obx_int.IdUid(5, 1789566561207249054),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1731803144609708519),
        name: 'idCategory',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6733728860544805392),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 9174613086877876733),
        name: 'level',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8407544899231393571),
        name: 'parent',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1789566561207249054),
        name: 'productId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 9153443521418966216),
        relationTarget: 'ProductBox',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 4128261350642884033),
    name: 'ProductBox',
    lastPropertyId: const obx_int.IdUid(9, 125886565802266517),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2320992625907644778),
        name: 'idProduct',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 371323129106173534),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2609593488037723415),
        name: 'price',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 282716519735822010),
        name: 'discount',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 509993225368686468),
        name: 'discountedPrice',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 354826701800105572),
        name: 'imageUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7435511298048066916),
        name: 'marks',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 4929892421484905170),
        name: 'stock',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 125886565802266517),
        name: 'description',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'categories',
        srcEntity: 'CategoryBox',
        srcField: 'product',
      ),
      obx_int.ModelBacklink(
        name: 'specifications',
        srcEntity: 'SpecificationBox',
        srcField: 'product',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 4554370860469021776),
    name: 'SpecificationBox',
    lastPropertyId: const obx_int.IdUid(5, 3403132717975881340),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8537528104654083296),
        name: 'idSpec',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2746280391028959154),
        name: 'attributeName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1041774987603650636),
        name: 'value',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 550751247195771875),
        name: 'productId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(2, 4504896009286587906),
        relationTarget: 'ProductBox',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3403132717975881340),
        name: 'attributeId',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 1391590698796611740),
    name: 'DeliveryAddressBox',
    lastPropertyId: const obx_int.IdUid(9, 3606986736891617364),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1217101285192197916),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5815903078799551594),
        name: 'deliveryType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7438553885857084763),
        name: 'comments',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1419605393681883263),
        name: 'pickupLocation',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5798831176627381852),
        name: 'country',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4887930276554479760),
        name: 'region',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3358737473617736461),
        name: 'city',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 3572427999256531823),
        name: 'postalCode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 3606986736891617364),
        name: 'address',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 5331394926556515126),
    name: 'PaymentMethodBox',
    lastPropertyId: const obx_int.IdUid(3, 4014327120835671699),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7504281067291536916),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 9158848028279639401),
        name: 'key',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4014327120835671699),
        name: 'titleKey',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 417593517334926949),
    name: 'UserBox',
    lastPropertyId: const obx_int.IdUid(6, 1361046753532434034),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1507152223618843587),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8842457239495892617),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7764263670518709320),
        name: 'surname',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7742160915400199029),
        name: 'number',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6445842672435435804),
        name: 'dialCode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1361046753532434034),
        name: 'email',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(6, 417593517334926949),
    lastIndexId: const obx_int.IdUid(2, 4504896009286587906),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    CategoryBox: obx_int.EntityDefinition<CategoryBox>(
      model: _entities[0],
      toOneRelations: (CategoryBox object) => [object.product],
      toManyRelations: (CategoryBox object) => {},
      getId: (CategoryBox object) => object.idCategory,
      setId: (CategoryBox object, int id) {
        object.idCategory = id;
      },
      objectToFB: (CategoryBox object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(6);
        fbb.addInt64(0, object.idCategory);
        fbb.addOffset(1, nameOffset);
        fbb.addInt64(2, object.level);
        fbb.addInt64(3, object.parent);
        fbb.addInt64(4, object.product.targetId);
        fbb.finish(fbb.endTable());
        return object.idCategory;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idCategoryParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final levelParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final parentParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          10,
        );
        final object = CategoryBox(
          idCategory: idCategoryParam,
          name: nameParam,
          level: levelParam,
          parent: parentParam,
        );
        object.product.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        object.product.attach(store);
        return object;
      },
    ),
    ProductBox: obx_int.EntityDefinition<ProductBox>(
      model: _entities[1],
      toOneRelations: (ProductBox object) => [],
      toManyRelations: (ProductBox object) => {
        obx_int.RelInfo<CategoryBox>.toOneBacklink(
          5,
          object.idProduct,
          (CategoryBox srcObject) => srcObject.product,
        ): object.categories,
        obx_int.RelInfo<SpecificationBox>.toOneBacklink(
          4,
          object.idProduct,
          (SpecificationBox srcObject) => srcObject.product,
        ): object.specifications,
      },
      getId: (ProductBox object) => object.idProduct,
      setId: (ProductBox object, int id) {
        object.idProduct = id;
      },
      objectToFB: (ProductBox object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final priceOffset = object.price == null
            ? null
            : fbb.writeString(object.price!);
        final discountOffset = object.discount == null
            ? null
            : fbb.writeString(object.discount!);
        final discountedPriceOffset = object.discountedPrice == null
            ? null
            : fbb.writeString(object.discountedPrice!);
        final imageUrlOffset = object.imageUrl == null
            ? null
            : fbb.writeString(object.imageUrl!);
        final marksOffset = object.marks == null
            ? null
            : fbb.writeString(object.marks!);
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        fbb.startTable(10);
        fbb.addInt64(0, object.idProduct);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, priceOffset);
        fbb.addOffset(3, discountOffset);
        fbb.addOffset(4, discountedPriceOffset);
        fbb.addOffset(5, imageUrlOffset);
        fbb.addOffset(6, marksOffset);
        fbb.addInt64(7, object.stock);
        fbb.addOffset(8, descriptionOffset);
        fbb.finish(fbb.endTable());
        return object.idProduct;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idProductParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final priceParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final discountParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final discountedPriceParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final imageUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final marksParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final stockParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          18,
        );
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final object = ProductBox(
          idProduct: idProductParam,
          name: nameParam,
          price: priceParam,
          discount: discountParam,
          discountedPrice: discountedPriceParam,
          imageUrl: imageUrlParam,
          marks: marksParam,
          stock: stockParam,
          description: descriptionParam,
        );
        obx_int.InternalToManyAccess.setRelInfo<ProductBox>(
          object.categories,
          store,
          obx_int.RelInfo<CategoryBox>.toOneBacklink(
            5,
            object.idProduct,
            (CategoryBox srcObject) => srcObject.product,
          ),
        );
        obx_int.InternalToManyAccess.setRelInfo<ProductBox>(
          object.specifications,
          store,
          obx_int.RelInfo<SpecificationBox>.toOneBacklink(
            4,
            object.idProduct,
            (SpecificationBox srcObject) => srcObject.product,
          ),
        );
        return object;
      },
    ),
    SpecificationBox: obx_int.EntityDefinition<SpecificationBox>(
      model: _entities[2],
      toOneRelations: (SpecificationBox object) => [object.product],
      toManyRelations: (SpecificationBox object) => {},
      getId: (SpecificationBox object) => object.idSpec,
      setId: (SpecificationBox object, int id) {
        object.idSpec = id;
      },
      objectToFB: (SpecificationBox object, fb.Builder fbb) {
        final attributeNameOffset = fbb.writeString(object.attributeName);
        final valueOffset = fbb.writeString(object.value);
        fbb.startTable(6);
        fbb.addInt64(0, object.idSpec);
        fbb.addOffset(1, attributeNameOffset);
        fbb.addOffset(2, valueOffset);
        fbb.addInt64(3, object.product.targetId);
        fbb.addInt64(4, object.attributeId);
        fbb.finish(fbb.endTable());
        return object.idSpec;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idSpecParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final attributeIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final attributeNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final valueParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final object = SpecificationBox(
          idSpec: idSpecParam,
          attributeId: attributeIdParam,
          attributeName: attributeNameParam,
          value: valueParam,
        );
        object.product.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        object.product.attach(store);
        return object;
      },
    ),
    DeliveryAddressBox: obx_int.EntityDefinition<DeliveryAddressBox>(
      model: _entities[3],
      toOneRelations: (DeliveryAddressBox object) => [],
      toManyRelations: (DeliveryAddressBox object) => {},
      getId: (DeliveryAddressBox object) => object.id,
      setId: (DeliveryAddressBox object, int id) {
        object.id = id;
      },
      objectToFB: (DeliveryAddressBox object, fb.Builder fbb) {
        final deliveryTypeOffset = fbb.writeString(object.deliveryType);
        final commentsOffset = object.comments == null
            ? null
            : fbb.writeString(object.comments!);
        final pickupLocationOffset = object.pickupLocation == null
            ? null
            : fbb.writeString(object.pickupLocation!);
        final countryOffset = object.country == null
            ? null
            : fbb.writeString(object.country!);
        final regionOffset = object.region == null
            ? null
            : fbb.writeString(object.region!);
        final cityOffset = object.city == null
            ? null
            : fbb.writeString(object.city!);
        final postalCodeOffset = object.postalCode == null
            ? null
            : fbb.writeString(object.postalCode!);
        final addressOffset = object.address == null
            ? null
            : fbb.writeString(object.address!);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, deliveryTypeOffset);
        fbb.addOffset(2, commentsOffset);
        fbb.addOffset(3, pickupLocationOffset);
        fbb.addOffset(4, countryOffset);
        fbb.addOffset(5, regionOffset);
        fbb.addOffset(6, cityOffset);
        fbb.addOffset(7, postalCodeOffset);
        fbb.addOffset(8, addressOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final deliveryTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final pickupLocationParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final countryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final regionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final cityParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final postalCodeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final addressParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final commentsParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final object = DeliveryAddressBox(
          id: idParam,
          deliveryType: deliveryTypeParam,
          pickupLocation: pickupLocationParam,
          country: countryParam,
          region: regionParam,
          city: cityParam,
          postalCode: postalCodeParam,
          address: addressParam,
          comments: commentsParam,
        );

        return object;
      },
    ),
    PaymentMethodBox: obx_int.EntityDefinition<PaymentMethodBox>(
      model: _entities[4],
      toOneRelations: (PaymentMethodBox object) => [],
      toManyRelations: (PaymentMethodBox object) => {},
      getId: (PaymentMethodBox object) => object.id,
      setId: (PaymentMethodBox object, int id) {
        object.id = id;
      },
      objectToFB: (PaymentMethodBox object, fb.Builder fbb) {
        final keyOffset = fbb.writeString(object.key);
        final titleKeyOffset = fbb.writeString(object.titleKey);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, keyOffset);
        fbb.addOffset(2, titleKeyOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final keyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final titleKeyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final object = PaymentMethodBox(
          id: idParam,
          key: keyParam,
          titleKey: titleKeyParam,
        );

        return object;
      },
    ),
    UserBox: obx_int.EntityDefinition<UserBox>(
      model: _entities[5],
      toOneRelations: (UserBox object) => [],
      toManyRelations: (UserBox object) => {},
      getId: (UserBox object) => object.id,
      setId: (UserBox object, int id) {
        object.id = id;
      },
      objectToFB: (UserBox object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final surnameOffset = fbb.writeString(object.surname);
        final numberOffset = fbb.writeString(object.number);
        final dialCodeOffset = fbb.writeString(object.dialCode);
        final emailOffset = fbb.writeString(object.email);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, surnameOffset);
        fbb.addOffset(3, numberOffset);
        fbb.addOffset(4, dialCodeOffset);
        fbb.addOffset(5, emailOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final surnameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final numberParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final dialCodeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final emailParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final object = UserBox(
          id: idParam,
          name: nameParam,
          surname: surnameParam,
          number: numberParam,
          dialCode: dialCodeParam,
          email: emailParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [CategoryBox] entity fields to define ObjectBox queries.
class CategoryBox_ {
  /// See [CategoryBox.idCategory].
  static final idCategory = obx.QueryIntegerProperty<CategoryBox>(
    _entities[0].properties[0],
  );

  /// See [CategoryBox.name].
  static final name = obx.QueryStringProperty<CategoryBox>(
    _entities[0].properties[1],
  );

  /// See [CategoryBox.level].
  static final level = obx.QueryIntegerProperty<CategoryBox>(
    _entities[0].properties[2],
  );

  /// See [CategoryBox.parent].
  static final parent = obx.QueryIntegerProperty<CategoryBox>(
    _entities[0].properties[3],
  );

  /// See [CategoryBox.product].
  static final product = obx.QueryRelationToOne<CategoryBox, ProductBox>(
    _entities[0].properties[4],
  );
}

/// [ProductBox] entity fields to define ObjectBox queries.
class ProductBox_ {
  /// See [ProductBox.idProduct].
  static final idProduct = obx.QueryIntegerProperty<ProductBox>(
    _entities[1].properties[0],
  );

  /// See [ProductBox.name].
  static final name = obx.QueryStringProperty<ProductBox>(
    _entities[1].properties[1],
  );

  /// See [ProductBox.price].
  static final price = obx.QueryStringProperty<ProductBox>(
    _entities[1].properties[2],
  );

  /// See [ProductBox.discount].
  static final discount = obx.QueryStringProperty<ProductBox>(
    _entities[1].properties[3],
  );

  /// See [ProductBox.discountedPrice].
  static final discountedPrice = obx.QueryStringProperty<ProductBox>(
    _entities[1].properties[4],
  );

  /// See [ProductBox.imageUrl].
  static final imageUrl = obx.QueryStringProperty<ProductBox>(
    _entities[1].properties[5],
  );

  /// See [ProductBox.marks].
  static final marks = obx.QueryStringProperty<ProductBox>(
    _entities[1].properties[6],
  );

  /// See [ProductBox.stock].
  static final stock = obx.QueryIntegerProperty<ProductBox>(
    _entities[1].properties[7],
  );

  /// See [ProductBox.description].
  static final description = obx.QueryStringProperty<ProductBox>(
    _entities[1].properties[8],
  );

  /// see [ProductBox.categories]
  static final categories = obx.QueryBacklinkToMany<CategoryBox, ProductBox>(
    CategoryBox_.product,
  );

  /// see [ProductBox.specifications]
  static final specifications =
      obx.QueryBacklinkToMany<SpecificationBox, ProductBox>(
        SpecificationBox_.product,
      );
}

/// [SpecificationBox] entity fields to define ObjectBox queries.
class SpecificationBox_ {
  /// See [SpecificationBox.idSpec].
  static final idSpec = obx.QueryIntegerProperty<SpecificationBox>(
    _entities[2].properties[0],
  );

  /// See [SpecificationBox.attributeName].
  static final attributeName = obx.QueryStringProperty<SpecificationBox>(
    _entities[2].properties[1],
  );

  /// See [SpecificationBox.value].
  static final value = obx.QueryStringProperty<SpecificationBox>(
    _entities[2].properties[2],
  );

  /// See [SpecificationBox.product].
  static final product = obx.QueryRelationToOne<SpecificationBox, ProductBox>(
    _entities[2].properties[3],
  );

  /// See [SpecificationBox.attributeId].
  static final attributeId = obx.QueryIntegerProperty<SpecificationBox>(
    _entities[2].properties[4],
  );
}

/// [DeliveryAddressBox] entity fields to define ObjectBox queries.
class DeliveryAddressBox_ {
  /// See [DeliveryAddressBox.id].
  static final id = obx.QueryIntegerProperty<DeliveryAddressBox>(
    _entities[3].properties[0],
  );

  /// See [DeliveryAddressBox.deliveryType].
  static final deliveryType = obx.QueryStringProperty<DeliveryAddressBox>(
    _entities[3].properties[1],
  );

  /// See [DeliveryAddressBox.comments].
  static final comments = obx.QueryStringProperty<DeliveryAddressBox>(
    _entities[3].properties[2],
  );

  /// See [DeliveryAddressBox.pickupLocation].
  static final pickupLocation = obx.QueryStringProperty<DeliveryAddressBox>(
    _entities[3].properties[3],
  );

  /// See [DeliveryAddressBox.country].
  static final country = obx.QueryStringProperty<DeliveryAddressBox>(
    _entities[3].properties[4],
  );

  /// See [DeliveryAddressBox.region].
  static final region = obx.QueryStringProperty<DeliveryAddressBox>(
    _entities[3].properties[5],
  );

  /// See [DeliveryAddressBox.city].
  static final city = obx.QueryStringProperty<DeliveryAddressBox>(
    _entities[3].properties[6],
  );

  /// See [DeliveryAddressBox.postalCode].
  static final postalCode = obx.QueryStringProperty<DeliveryAddressBox>(
    _entities[3].properties[7],
  );

  /// See [DeliveryAddressBox.address].
  static final address = obx.QueryStringProperty<DeliveryAddressBox>(
    _entities[3].properties[8],
  );
}

/// [PaymentMethodBox] entity fields to define ObjectBox queries.
class PaymentMethodBox_ {
  /// See [PaymentMethodBox.id].
  static final id = obx.QueryIntegerProperty<PaymentMethodBox>(
    _entities[4].properties[0],
  );

  /// See [PaymentMethodBox.key].
  static final key = obx.QueryStringProperty<PaymentMethodBox>(
    _entities[4].properties[1],
  );

  /// See [PaymentMethodBox.titleKey].
  static final titleKey = obx.QueryStringProperty<PaymentMethodBox>(
    _entities[4].properties[2],
  );
}

/// [UserBox] entity fields to define ObjectBox queries.
class UserBox_ {
  /// See [UserBox.id].
  static final id = obx.QueryIntegerProperty<UserBox>(
    _entities[5].properties[0],
  );

  /// See [UserBox.name].
  static final name = obx.QueryStringProperty<UserBox>(
    _entities[5].properties[1],
  );

  /// See [UserBox.surname].
  static final surname = obx.QueryStringProperty<UserBox>(
    _entities[5].properties[2],
  );

  /// See [UserBox.number].
  static final number = obx.QueryStringProperty<UserBox>(
    _entities[5].properties[3],
  );

  /// See [UserBox.dialCode].
  static final dialCode = obx.QueryStringProperty<UserBox>(
    _entities[5].properties[4],
  );

  /// See [UserBox.email].
  static final email = obx.QueryStringProperty<UserBox>(
    _entities[5].properties[5],
  );
}
