name: di
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: 'none'

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  domain:
    path: ../domain
  data:
    path: ../data
  common:
    path: ../common
  dio: ^5.8.0+1
  get_it: ^8.0.3
  objectbox: ^4.3.1
  objectbox_flutter_libs: any
  # path: ^1.8.0

dev_dependencies:
  objectbox_generator: any
  lints: ^6.0.0
  test: ^1.24.0
